name: Publish Docker

on: workflow_dispatch

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_REGISTRY}}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ vars.HARBOR_REGISTRY}}/library/excalidraw:latest
            ${{ vars.HARBOR_REGISTRY}}/library/excalidraw:0.17.6-${{ github.run_id }}
